subdir-ccflags-y += -I$(srctree)/drivers/micro_dump
subdir-ccflags-y += -I$(srctree)/include/
subdir-ccflags-y += -I$(srctree)/kernel/
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/aee/mrdump/
obj-$(CONFIG_HN_MICRODUMP) += micro_dump.o irq_dump.o out_print.o page_dump.o policy.o process_dump.o register_dump.o sched_dump.o stack_dump.o bitflip.o undef_dump.o
obj-$(CONFIG_HN_MICRODUMP_TEST) += micro_test.o
