mm_stats-$(CONFIG_MEM_REPORT) := mem_report.o
mm_stats-$(CONFIG_MEM_DETECT) += mem_detect.o
mm_stats-y += mem_stats_sysfs.o
obj-$(CONFIG_MEM_STATS) += mm_stats.o
obj-$(CONFIG_MEMORY_MONITOR) += mmonitor/
obj-$(CONFIG_RECLAIM_ACCT) += reclaim_acct/
obj-$(CONFIG_DEBUG_PAGE_LOCK) += page_lock/
obj-$(CONFIG_HONOR_MEMLOCK_STATS) += memlock_stats/
